/*
 * generated by Xtext
 */
package org.xtext.xrobot.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.xrobot.dsl.ui.internal.XRobotDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XRobotDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XRobotDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XRobotDSLActivator.getInstance().getInjector(XRobotDSLActivator.ORG_XTEXT_XROBOT_DSL_XROBOTDSL);
	}
	
}
