/*
 * generated by Xtext
 */
package org.xtext.xrobot.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XRobotDSLUiModule extends org.xtext.xrobot.dsl.ui.AbstractXRobotDSLUiModule {
	public XRobotDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
