/*
 * generated by Xtext
 */
package org.xtext.xrobot.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XRobotDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.xrobot.dsl.ui.internal.XRobotDSLActivator.getInstance().getInjector("org.xtext.xrobot.dsl.XRobotDSL");
	}
	
}
