/*
 * generated by Xtext
 */
package org.xtext.xrobot.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.xrobot.dsl.services.XRobotDSLGrammarAccess;

public class XRobotDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XRobotDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.xrobot.dsl.parser.antlr.internal.InternalXRobotDSLParser createParser(XtextTokenStream stream) {
		return new org.xtext.xrobot.dsl.parser.antlr.internal.InternalXRobotDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public XRobotDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XRobotDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
