/*
 * generated by Xtext
 */
package org.xtext.xrobot.dsl.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XRobotDSLProposalProvider extends AbstractXRobotDSLProposalProvider {
}
