/*
 * generated by Xtext
 */
package org.xtext.xrobot.dsl;

import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.xbase.scoping.batch.FeatureScopes;
import org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedFeatures;
import org.xtext.xrobot.dsl.scoping.XRobotFeatureScopes;
import org.xtext.xrobot.dsl.scoping.XRobotImplicitlyImportedFeatures;
import org.xtext.xrobot.dsl.scoping.XRobotResourceDescriptionStrategy;
import org.xtext.xrobot.server.IRemoteRobot;
import org.xtext.xrobot.server.RemoteRobotConnector;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("restriction")
public class XRobotDSLRuntimeModule extends org.xtext.xrobot.dsl.AbstractXRobotDSLRuntimeModule {

	public Class<? extends ImplicitlyImportedFeatures> bindImplicitlyImportedFeatures() {
		return XRobotImplicitlyImportedFeatures.class;
	}
	
	public Class<? extends IRemoteRobot.Connector> bindIRemoteRobot$Connector() {
		return RemoteRobotConnector.class;
	}
	
	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return XRobotResourceDescriptionStrategy.class;
	}
	
	public Class<? extends IGenerator> bindIGenerator() {
		return IGenerator.NullGenerator.class;
	}
	
	public Class<? extends FeatureScopes> bindFeatureScopes() {
		return XRobotFeatureScopes.class;
	}
}
