/*
* generated by Xtext
*/
package org.xtext.xrobot.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XRobotDSLStandaloneSetup extends XRobotDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new XRobotDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

