/**
 * generated by Xtext
 */
package org.xtext.xrobot.dsl.validation;

import org.xtext.xrobot.dsl.validation.AbstractXRobotDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XRobotDSLValidator extends AbstractXRobotDSLValidator {
}
